In [2]:
import pandas as pd
df_upgradeData = pd.read_excel("강화데이터.xlsx")
df_upgradeData

    강화수치  강화성공확률  소모주문서  전설보조제    전설골드  영웅보조제    영웅골드  희귀보조제     희귀골드
0      0     100      1      0   15000      0   10000    0.0   3000.0
1      1     100      1      0   15000      0   10000    0.0   3000.0
2      2     100      1      0   15000      0   10000    0.0   9000.0
3      3      90      1      3   45000      2   30000    1.0   9000.0
4      4      80      1      6   45000      4   30000    2.0   9000.0
5      5      70      1      6   45000      4   30000    2.0  12000.0
6      6      50      1      9   60000      6   40000    4.0  12000.0
7      7      35      1      9   60000      6   40000    4.0  12000.0
8      8      20      1     12   60000      8   40000    5.0  15000.0
9      9      10      2     12   75000      8   50000    5.0  15000.0
10    10      45      2      0   75000      0   50000    0.0  15000.0
11    11      40      2     15   75000     10   50000    6.0  18000.0
12    12      35      2     15   90000     10   60000    6.0      NaN
13    13      30      2     18   90000     12   60000    NaN      NaN
14    14      25      2     18   90000     12   60000    NaN      NaN
15    15      20      2     18   90000     14   80000    NaN      NaN
16    16      15      2     21  120000     14   80000    NaN      NaN
17    17      10      2     21  120000     16   80000    NaN      NaN
18    18       7      2     24  150000     16  100000    NaN      NaN
19    19       5      2     30  150000     20  100000    NaN      NaN

In [3]:
data = {
    '시뮬레이션횟수':[0],
    '소모골드':[0],
    '소모보조제':[0],
    '소모주문서':[0],
    '강화횟수':[0],
    '0등급강화횟수':[0],
    '1등급강화횟수':[0],
    '2등급강화횟수':[0],
    '3등급강화횟수':[0],
    '4등급강화횟수':[0],
    '5등급강화횟수':[0],
    '6등급강화횟수':[0],
    '7등급강화횟수':[0],
    '8등급강화횟수':[0],
    '9등급강화횟수':[0],
    '10등급강화횟수':[0],
    '11등급강화횟수':[0],
    '12등급강화횟수':[0],
    '13등급강화횟수':[0],
    '14등급강화횟수':[0],
    '15등급강화횟수':[0],
    '16등급강화횟수':[0],
    '17등급강화횟수':[0],
    '18등급강화횟수':[0],
    '19등급강화횟수':[0]
}

In [4]:
df_simul = pd.DataFrame(data)
df_simulTotal = pd.DataFrame(data)
df_simul

,시뮬레이션횟수,소모골드,소모보조제,강화횟수,0등급강화횟수,1등급강화횟수,2등급강화횟수,3등급강화횟수,4등급강화횟수,5등급강화횟수,...,10등급강화횟수,11등급강화횟수,12등급강화횟수,13등급강화횟수,14등급강화횟수,15등급강화횟수,16등급강화횟수,17등급강화횟수,18등급강화횟수,19등급강화횟수
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
import random
시뮬레이션횟수 = input("시뮬레이션 횟수를 적어주세요")
장비등급 = input("장비등급을 적어주세요. (전설, 영웅, 희귀)")
시작등급 = input("시작 등급을 적어주세요 : ")
목표등급 = input("강화 목표 등급을 적어주세요 : ")

def 시뮬레이션(시뮬횟수):
    현재시뮬횟수 = 0
    while 현재시뮬횟수 != int(시뮬횟수):
        df_simul = 기본강화(시작등급)
        df_simulTotal.append(df_simul, ignore_index = True)
        df_simulTotal.loc[현재시뮬횟수] = [현재시뮬횟수, df_simul.loc[0,"소모골드"],df_simul.loc[0,"소모보조제"], df_simul.loc[0,"강화횟수"], df_simul.loc[0,"0등급강화횟수"],
                                        df_simul.loc[0,"1등급강화횟수"],df_simul.loc[0,"2등급강화횟수"],df_simul.loc[0,"3등급강화횟수"], df_simul.loc[0,"4등급강화횟수"],
                                     df_simul.loc[0,"5등급강화횟수"], df_simul.loc[0,"6등급강화횟수"], df_simul.loc[0,"7등급강화횟수"], df_simul.loc[0,"8등급강화횟수"],
                                     df_simul.loc[0,"9등급강화횟수"], df_simul.loc[0,"10등급강화횟수"], df_simul.loc[0,"11등급강화횟수"], df_simul.loc[0,"12등급강화횟수"],
                                     df_simul.loc[0,"13등급강화횟수"],df_simul.loc[0,"14등급강화횟수"],df_simul.loc[0,"15등급강화횟수"], df_simul.loc[0,"16등급강화횟수"],
                                     df_simul.loc[0,"17등급강화횟수"], df_simul.loc[0,"18등급강화횟수"], df_simul.loc[0,"19등급강화횟수"]]
        현재시뮬횟수 += 1
        
    return df_simulTotal

def 기본강화(시작등급):
    강화등급 = int(시작등급)
    강화횟수 = 0
    소모골드 = 0
    소모보조제 = 0
    df_simul = pd.DataFrame(data)
    while 강화등급 != int(목표등급):
        강화횟수 +=1
        등급별강화횟수 = df_simul.loc[0, str(강화등급) + "등급강화횟수"]
        df_simul.loc[0, str(강화등급) + "등급강화횟수"] = 등급별강화횟수 + 1
        소모골드 += df_upgradeData[장비등급 + "골드"][강화등급]
        소모보조제 += df_upgradeData[장비등급 + "보조제"][강화등급]
        소모주문서 +=  df_upgradeData["소모주문서"][강화등급]
        성공여부 = random.random()
        if df_upgradeData.iloc[강화등급,1] >= 성공여부*100:
            강화등급 += 1
        else:
            if 강화등급 == 10:
                강화등급 == 10
            else:
                강화등급 -= 1
    df_simul.loc[0,"소모골드"] = 소모골드
    df_simul.loc[0,"강화횟수"] = 강화횟수
    df_simul.loc[0, "소모보조제"] = 소모보조제
    df_simul.loc[0, "소모주문서"] = 소모주문서
    df_simulTotal.append(df_simul, ignore_index = True)
    
    return df_simul
    
#시뮬레이션(시뮬레이션횟수)
df = 시뮬레이션(시뮬레이션횟수)
df